### ISSUE TITLE
Missing mapquest_inc/fontset-settings.xml.inc file

### ISSUE THREAD

**Issue by ajturner** [MapQuest/MapQuest-Mapnik-Style#1]
There seems to be some missing files:

$ nik2img.py mapquest-us.xml > mapquest.png

I/O warning : failed to load external entity "mapquest_inc/fontset-settings.xml.inc"

**Comment by ajturner** [comment]
also missing: "mapquest_inc/settings.xml.inc"

**Comment by tlperkins** [comment]
Our system follows the same format as the default OSM style.  That means that  the *.template file need to be supplied and are standard.  We will include the default template files in a future revision.

**Comment by artemp** [comment]
missing settings files are added in 65e15dbd589fb9045cbca59145ee87fedf5b661c
using OSM .template format
