### ISSUE TITLE
name:en with updates2 branch

### ISSUE THREAD

**Issue by pnorman** [MapQuest/MapQuest-Mapnik-Style#10]
Using the stylesheet with the updates2 branch resulted in the error

```
column "name:en" does not exist
```

Adding a name:en column to the .style used by osm2pgsql fixed this. This should be documented.

**Comment by zerebubuth** [comment]
Thanks for pointing this out. I've added documentation and the osm2pgsql style file we use in commit 3e490eae4b8. Hopefully this addresses the missing `name:en` error you mention.
