### ISSUE TITLE
Disused railway stations shown as normal

### ISSUE THREAD

**Issue by mackerski** [MapQuest/MapQuest-Mapnik-Style#13]
Railway stations with tag disused=yes should (probably) not be shown in a standard rendering, at least not in the same style as normal ones. Example is this London MailRail station: http://mapq.st/R81feK

**Comment by gravitystorm** [comment]
That's incorrect tagging in osm, see e.g. http://lists.openstreetmap.org/pipermail/talk-gb/2011-April/011460.html

Adding logic to the style would just be perpetuating the problem. Better to remove the tag from the station.

**Comment by mackerski** [comment]
Well, "incorrect" is in the eye of the beholder, but yes, I mostly buy your logic as expressed in the linked mail. Seems that we ought to offer a one-true-tag for disused stations, though.
