### ISSUE TITLE
House numbers not rendered for polygons tagged as building=house

### ISSUE THREAD

**Issue by Jonobennett** [MapQuest/MapQuest-Mapnik-Style#3]
While this style shows house numbers for any building tagged as `building=yes` but not for `building=house`.

This can be seen here:

http://open.mapquest.co.uk/link/9-9tsphqP6

The first few houses in Guildford Park Avenue are `building=yes`, while all the houses in Lynwood are `building=house`.

**Comment by gravitystorm** [comment]
Thanks, fixed in 8f090b212c67c26d171ba63e7af7d34b21f62234
