### ISSUE TITLE
Path mismatch

### ISSUE THREAD

**Issue by pnorman** [MapQuest/MapQuest-Mapnik-Style#9]
When rendering a map with the style it has the error

```
### WARNING Marker does not exist: /home/pnorman/osm/mapnik/MapQuest-Mapnik-Style/symbols/shield_sr_us2.svg
```

Either it should be changed to look in mapquest_symbols or mapquest_symbols should be renamed

**Comment by zerebubuth** [comment]
The directory that the style looks in to find the symbols is controlled in the settings.xml.inc in either the mapquest_inc/ directory or the hybrid_inc/ directory. The suggestion in the file that 'symbols' should be used is misleading and I have made that better in commit 6f7ea2723c. If setting this entity to 'mapquest_symbols' doesn't fix the problem, please let me know.
